version: "3"

services :
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: t_db
    ports:
      - "3306:3306"
    volumes:
      - ./sql/database_v2.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSORD: pass
      MYSQL_DATABASE: mydb
    working_dir: /home
    networks: 
      - default
      
  web:
    build:
      context: ./python
      dockerfile: Dockerfile_python
    container_name: t_python
    depends_on: 
      - db
    ports:
      - "5000:5000"
    volumes:
    - ./python/:/home/
    networks:
      - default

  

# Permet l'établissement d'un réseau, lequel sera donné à chaque service
networks:
  default:
